# Generated by Django 4.0 on 2022-01-06 16:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_student_current_aa_student_is_in_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_status', models.CharField(blank=True, choices=[('In review', 'In review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='In review', max_length=20)),
                ('visibility_for_employer', models.BooleanField(blank=True, default=False)),
                ('application_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('has_ended', models.BooleanField(blank=True, default=False)),
                ('has_started', models.BooleanField(blank=True, default=False)),
                ('confirm', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewProfile',
            fields=[
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.employer')),
                ('review_status', models.CharField(blank=True, choices=[('In review', 'In review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='In review', max_length=20)),
                ('reason', models.TextField(blank=True, max_length=100, null=True)),
                ('admin_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.giuadmin')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('progress_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_report_title', models.CharField(blank=True, max_length=100)),
                ('progress_report_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('numeric_state', models.PositiveIntegerField(blank=True, default=0)),
                ('evaluation', models.TextField(blank=True, default='', max_length=300)),
                ('progress_report_description', models.TextField(blank=True, default='', max_length=1000)),
                ('academic_advisor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.academicadvisor')),
                ('application_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.application')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('job_description', models.TextField(max_length=1000)),
                ('department', models.CharField(max_length=20)),
                ('job_start_date', models.DateField()),
                ('job_end_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('num_of_available_internships', models.PositiveIntegerField()),
                ('salary_range', models.CharField(max_length=20)),
                ('qualifications', models.TextField(max_length=500)),
                ('job_location', models.CharField(max_length=20)),
                ('application_link', models.CharField(blank=True, max_length=50, null=True)),
                ('application_email', models.CharField(blank=True, max_length=50, null=True)),
                ('job_type', models.CharField(choices=[('Industrial Internship', 'Industrial Internship'), ('Other', 'Other')], max_length=30)),
                ('allowed_faculties', models.TextField(choices=[('Engineering', 'Engineering'), ('Computer Science', 'Computer Science'), ('Business', 'Business'), ('Design', 'Design'), ('Architecture', 'Architecture'), ('Biotechnology', 'Biotechnology'), ('Pharmaceutical', 'Pharmaceutical')], max_length=300)),
                ('required_semesters', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], max_length=20)),
                ('visibility_fac_rep', models.BooleanField(blank=True, default=False)),
                ('visibility_admin', models.BooleanField(blank=True, default=False, verbose_name='Visibility')),
                ('post_is_up', models.BooleanField(default=True, verbose_name='Visible')),
                ('aa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.academicadvisor')),
                ('active_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.student')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employer')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.job'),
        ),
        migrations.AddField(
            model_name='application',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student_id', 'job_id')},
        ),
    ]
