# Generated by Django 4.0 on 2021-12-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0014_remove_cvbuilder_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('job_description', models.TextField(max_length=50)),
                ('department', models.CharField(max_length=20)),
                ('job_start_date', models.DateField()),
                ('job_end_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('num_of_available_internships', models.PositiveIntegerField()),
                ('salary_range', models.CharField(max_length=20)),
                ('qualifications', models.TextField(max_length=100)),
                ('job_location', models.CharField(max_length=20)),
                ('application_link', models.CharField(max_length=50)),
                ('application_email', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=30)),
                ('visibility', models.BooleanField(blank=True, default=False)),
                ('reason', models.TextField(max_length=100)),
                ('allowed_faculties', models.TextField(max_length=300)),
                ('required_semesters', models.CharField(max_length=20)),
                ('admin_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.giuadmin')),
                ('employer_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.employer')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewProfile',
            fields=[
                ('employer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.employer')),
                ('review_status', models.CharField(max_length=20)),
                ('reason', models.TextField(max_length=100)),
                ('admin_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.giuadmin')),
            ],
            options={
                'unique_together': {('employer_id', 'admin_id')},
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.student')),
                ('progress_report_date', models.DateField()),
                ('numeric_state', models.PositiveIntegerField()),
                ('evaluation', models.TextField(max_length=300)),
                ('progress_report_description', models.CharField(max_length=100)),
                ('academic_advisor_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.academicadvisor')),
            ],
            options={
                'unique_together': {('student_id', 'academic_advisor_id')},
            },
        ),
        migrations.CreateModel(
            name='IndustrialInternship',
            fields=[
                ('industrial_internship_ID', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='portal.job')),
                ('industrial_Internship_status', models.CharField(max_length=20)),
                ('aa_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.academicadvisor')),
                ('faculty_rep', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.facultyrepresentative')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.student')),
                ('application_status', models.CharField(max_length=20)),
                ('job_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.job')),
            ],
            options={
                'unique_together': {('student_id', 'job_id')},
            },
        ),
        migrations.CreateModel(
            name='Eligible',
            fields=[
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.student')),
                ('eligibility', models.BooleanField()),
                ('coc_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.careerofficecoordinator')),
                ('II_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.industrialinternship')),
            ],
            options={
                'unique_together': {('student_id', 'II_id')},
            },
        ),
    ]
