# Generated by Django 4.0 on 2022-01-03 08:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0022_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('progress_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_report_title', models.CharField(blank=True, max_length=100)),
                ('progress_report_date', models.DateField(blank=True, default=datetime.datetime(2022, 1, 3, 10, 57, 2, 453883))),
                ('numeric_state', models.PositiveIntegerField(blank=True, default=0)),
                ('evaluation', models.TextField(blank=True, default='', max_length=300)),
                ('progress_report_description', models.TextField(blank=True, default='', max_length=1000)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('job_description', models.TextField(max_length=1000)),
                ('department', models.CharField(max_length=20)),
                ('job_start_date', models.DateField()),
                ('job_end_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('num_of_available_internships', models.PositiveIntegerField()),
                ('salary_range', models.CharField(max_length=20)),
                ('qualifications', models.TextField(max_length=500)),
                ('job_location', models.CharField(max_length=20)),
                ('application_link', models.CharField(blank=True, max_length=50, null=True)),
                ('application_email', models.CharField(blank=True, max_length=50, null=True)),
                ('job_type', models.CharField(max_length=30)),
                ('allowed_faculties', models.TextField(max_length=300)),
                ('required_semesters', models.CharField(max_length=20)),
                ('visibility_fac_rep', models.BooleanField(blank=True, default=False)),
                ('visibility_admin', models.BooleanField(blank=True, default=False)),
                ('aa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.academicadvisor')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.employer')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewProfile',
            fields=[
                ('employer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.employer')),
                ('review_status', models.CharField(blank=True, default='In review', max_length=20)),
                ('reason', models.TextField(blank=True, max_length=100, null=True)),
                ('admin_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.giuadmin')),
            ],
            options={
                'unique_together': {('employer_id', 'admin_id')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_status', models.CharField(blank=True, default='In review', max_length=20)),
                ('visibility_for_employer', models.BooleanField(blank=True, default=False)),
                ('application_date', models.DateField(blank=True, default=datetime.datetime(2022, 1, 3, 10, 57, 2, 453883))),
                ('has_ended', models.BooleanField(blank=True, default=False)),
                ('has_started', models.BooleanField(blank=True, default=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.job')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.student')),
            ],
            options={
                'unique_together': {('student_id', 'job_id')},
            },
        ),
    ]
