# Generated by Django 4.0 on 2021-12-30 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_employer_employer_address'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewprofile',
            name='admin_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.giuadmin'),
        ),
        migrations.AlterField(
            model_name='reviewprofile',
            name='reason',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reviewprofile',
            name='review_status',
            field=models.CharField(blank=True, default='In review', max_length=20),
        ),
    ]
