# Generated by Django 4.0 on 2022-01-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_reviewprofile_admin_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='reason',
        ),
        migrations.AlterField(
            model_name='job',
            name='application_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
