# Generated by Django 4.0 on 2022-01-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_is_staff'),
        ('portal', '0003_remove_job_admin_id_remove_job_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.employer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.TextField(max_length=500),
        ),
    ]
