# Generated by Django 4.0 on 2022-01-01 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_is_staff'),
        ('portal', '0004_alter_job_employer_id_alter_job_job_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='visibility',
            new_name='visibility_admin',
        ),
        migrations.AlterUniqueTogether(
            name='eligible',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eligible',
            name='job_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='aa_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.academicadvisor'),
        ),
        migrations.AddField(
            model_name='job',
            name='faculty_rep',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.facultyrepresentative'),
        ),
        migrations.AddField(
            model_name='job',
            name='visibility_fac_rep',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterUniqueTogether(
            name='eligible',
            unique_together={('student_id', 'job_id')},
        ),
        migrations.RemoveField(
            model_name='eligible',
            name='II_id',
        ),
        migrations.DeleteModel(
            name='IndustrialInternship',
        ),
    ]
