# Generated by Django 4.0 on 2022-01-03 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_application_application_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='has_ended',
        ),
        migrations.RemoveField(
            model_name='job',
            name='has_started',
        ),
        migrations.AddField(
            model_name='application',
            name='has_ended',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='has_started',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 3, 2, 37, 25, 963321)),
        ),
    ]
