# Generated by Django 4.0 on 2022-01-04 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_application_application_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 4, 18, 7, 13, 539865)),
        ),
        migrations.AlterField(
            model_name='job',
            name='visibility_admin',
            field=models.BooleanField(blank=True, default=False, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='progress_report_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 4, 18, 7, 13, 539865)),
        ),
    ]
