# Generated by Django 4.0 on 2022-01-03 01:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_job_has_ended_remove_job_has_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='application_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.application'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 3, 3, 45, 35, 567225)),
        ),
    ]
