# Generated by Django 4.0 on 2022-01-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_rename_visibility_job_visibility_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='visibility_Coc',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='has_ended',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
