# Generated by Django 4.0 on 2022-01-03 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_progressreport_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='progress_report_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 3, 4, 47, 33, 181633)),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='progress_report_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 3, 4, 47, 33, 197292)),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='progress_report_description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
