# Generated by Django 4.0 on 2022-01-04 18:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_delete_faculties'),
        ('portal', '0013_alter_application_application_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='active_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.student'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 4, 20, 0, 31, 434686)),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='progress_report_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 4, 20, 0, 31, 434686)),
        ),
    ]
