# Generated by Django 4.0 on 2022-01-04 18:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_student_current_aa'),
        ('portal', '0015_alter_application_application_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='academic_advisor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.academicadvisor'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 4, 20, 44, 35, 453959)),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='progress_report_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 4, 20, 44, 35, 453959)),
        ),
    ]
