# Generated by Django 4.0 on 2022-01-04 19:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_student_current_aa'),
        ('portal', '0017_remove_job_active_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='active_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.student'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='application_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 4, 21, 41, 43, 182613)),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.job'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employer'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='academic_advisor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.academicadvisor'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='progress_report_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 4, 21, 41, 43, 182613)),
        ),
    ]
