# Generated by Django 4.0 on 2022-01-04 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_alter_application_application_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='post_is_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 5, 0, 21, 36, 343501)),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='progress_report_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 5, 0, 21, 36, 343501)),
        ),
    ]
