# Generated by Django 4.0 on 2022-01-04 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_job_post_is_up_alter_application_application_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='confirm',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 5, 1, 20, 27, 996448)),
        ),
        migrations.AlterField(
            model_name='job',
            name='post_is_up',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='progress_report_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 5, 1, 20, 27, 996448)),
        ),
    ]
