# Generated by Django 4.0 on 2022-01-05 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_application_confirm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 5, 2, 13, 8, 961519)),
        ),
        migrations.AlterField(
            model_name='job',
            name='allowed_faculties',
            field=models.TextField(choices=[('Engineering', 'Engineering'), ('Computer Science', 'Computer Science'), ('Business', 'Business'), ('Design', 'Design'), ('Architecture', 'Architecture'), ('Biotechnology', 'Biotechnology'), ('Pharmaceutical', 'Pharmaceutical')], max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_semesters',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], max_length=20),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='progress_report_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 5, 2, 13, 8, 961519)),
        ),
    ]
