# Generated by Django 4.0 on 2021-12-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eligable',
            new_name='Eligible',
        ),
    ]
