# Generated by Django 4.0 on 2021-12-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_eligable_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cover_letter',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
