# Generated by Django 4.0 on 2021-12-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='has_cv',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_university_id',
        ),
    ]
