# Generated by Django 4.0 on 2021-12-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_student_birthdate_alter_student_cover_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvbuilder',
            name='student_id',
        ),
        migrations.AlterUniqueTogether(
            name='eligible',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eligible',
            name='II_id',
        ),
        migrations.RemoveField(
            model_name='eligible',
            name='coc_id',
        ),
        migrations.RemoveField(
            model_name='eligible',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='industrialinternship',
            name='aa_id',
        ),
        migrations.RemoveField(
            model_name='industrialinternship',
            name='faculty_rep',
        ),
        migrations.RemoveField(
            model_name='industrialinternship',
            name='industrial_internship_ID',
        ),
        migrations.RemoveField(
            model_name='job',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employer_id',
        ),
        migrations.AlterUniqueTogether(
            name='progressreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='progressreport',
            name='academic_advisor_id',
        ),
        migrations.RemoveField(
            model_name='progressreport',
            name='student_id',
        ),
        migrations.AlterUniqueTogether(
            name='reviewprofile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reviewprofile',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='reviewprofile',
            name='employer_id',
        ),
        migrations.AlterField(
            model_name='employer',
            name='number_of_current_employees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='CvBuilder',
        ),
        migrations.DeleteModel(
            name='Eligible',
        ),
        migrations.DeleteModel(
            name='IndustrialInternship',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='ProgressReport',
        ),
        migrations.DeleteModel(
            name='ReviewProfile',
        ),
    ]
