# Generated by Django 4.0 on 2021-12-30 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_cvbuilder_student_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentphonenumbers',
            unique_together=set(),
        ),
    ]
