# Generated by Django 4.0 on 2021-12-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_studentphonenumbers_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(blank=True, default='company_images/default.png', max_length=1000, null=True, upload_to='C:\\Users\\iyade\\PycharmProjects\\Python-Personal-Projects\\GIU_Internship_Portal\\media/company_images/'),
        ),
    ]
