# Generated by Django 4.0 on 2021-12-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_employer_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='employer_address',
            field=models.CharField(max_length=40),
        ),
    ]
