# Generated by Django 4.0 on 2021-12-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_contactperson_contact_person_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='contact_person_name',
            field=models.CharField(blank=True, default='None', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='fax',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='job_title',
            field=models.CharField(blank=True, default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='mobile_number',
            field=models.CharField(blank=True, default='None', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hrdirector',
            name='hr_email',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hrdirector',
            name='hr_name',
            field=models.CharField(blank=True, default='None', max_length=20, null=True),
        ),
    ]
