# Generated by Django 4.0 on 2022-01-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='employer_address',
            field=models.CharField(max_length=100),
        ),
    ]
