# Generated by Django 4.0 on 2022-01-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_employer_employer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyrepresentative',
            name='rep_faculty',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
