# Generated by Django 4.0 on 2022-01-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_facultyrepresentative_rep_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyrepresentative',
            name='company_name',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
