# Generated by Django 4.0 on 2022-01-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_facultyrepresentative_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyrepresentative',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='facultyrepresentative',
            name='rep_faculty',
        ),
        migrations.AddField(
            model_name='facultyrepresentative',
            name='d',
            field=models.IntegerField(default=3),
        ),
    ]
