# Generated by Django 4.0 on 2022-01-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_facultyrepresentative_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('faculty_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
