# Generated by Django 4.0 on 2022-01-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_faculties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyrepresentative',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.faculties'),
        ),
    ]
