# Generated by Django 4.0 on 2022-01-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_facultyrepresentative_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyrepresentative',
            old_name='faculty',
            new_name='faculty_table',
        ),
    ]
