# Generated by Django 4.0 on 2022-01-04 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_rename_faculty_facultyrepresentative_faculty_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyrepresentative',
            name='faculty_table',
        ),
        migrations.AddField(
            model_name='faculties',
            name='facultyRep',
            field=models.OneToOneField(default=41, on_delete=django.db.models.deletion.DO_NOTHING, to='users.facultyrepresentative'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultyrepresentative',
            name='faculty',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
