# Generated by Django 4.0 on 2022-01-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_facultyrepresentative_faculty_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculties',
        ),
    ]
