# Generated by Django 4.0 on 2022-01-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_delete_faculties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('faculty_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('facultyRep', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.facultyrepresentative')),
            ],
        ),
    ]
