# Generated by Django 4.0 on 2022-01-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_faculties'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculties',
        ),
    ]
