# Generated by Django 4.0 on 2022-01-04 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_delete_faculties'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_aa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.academicadvisor'),
        ),
    ]
