# Generated by Django 4.0 on 2022-01-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_remove_student_current_aa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Computer Science', 'Computer Science'), ('Business', 'Business'), ('Design', 'Design'), ('Architecture', 'Architecture'), ('Biotechnology', 'Biotechnology'), ('Pharmaceutical', 'Pharmaceutical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)]),
        ),
    ]
