# Generated by Django 4.0 on 2021-12-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0014_remove_cvbuilder_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_phone', models.CharField(max_length=30)),
                ('personal_email', models.CharField(max_length=50)),
                ('education', models.TextField(max_length=100)),
                ('extracurricular_activities', models.TextField(max_length=300)),
                ('skills', models.TextField(max_length=300)),
                ('achievements', models.TextField(max_length=300)),
                ('languages', models.TextField(max_length=100)),
                ('interests', models.TextField(max_length=100)),
                ('experience', models.TextField(max_length=100)),
                ('linked_in_link', models.CharField(max_length=30)),
                ('github_link', models.CharField(max_length=30)),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.student')),
            ],
        ),
    ]
