# Generated by Django 4.0 on 2022-01-05 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_phone', models.CharField(max_length=30)),
                ('personal_email', models.CharField(max_length=50)),
                ('education', models.TextField(max_length=1000)),
                ('extracurricular_activities', models.TextField(max_length=2000)),
                ('skills', models.TextField(max_length=300)),
                ('achievements', models.TextField(max_length=1000)),
                ('languages', models.TextField(max_length=100)),
                ('interests', models.TextField(max_length=300)),
                ('experience', models.TextField(max_length=2000)),
                ('linked_in_link', models.CharField(max_length=30, null=True)),
                ('github_link', models.CharField(max_length=30, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profile_images/default.jpg', max_length=1000, null=True, upload_to='C:\\Users\\iyade\\PycharmProjects\\Python-Personal-Projects\\GIU_Internship_Portal\\media/profile_images/')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
