# Generated by Django 4.0 on 2021-12-29 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_cvbuilder_student_id_and_more'),
        ('cvbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvbuilder',
            name='github_link',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cvbuilder',
            name='linked_in_link',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cvbuilder',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
