# Generated by Django 4.0 on 2021-12-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0003_alter_cvbuilder_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvbuilder',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', null=True, upload_to='profile_images'),
        ),
    ]
