# Generated by Django 4.0 on 2021-12-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0004_cvbuilder_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvbuilder',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', max_length=1000, null=True, upload_to='C:\\Users\\iyade\\PycharmProjects\\Python-Personal-Projects\\GIU_Internship_Portal\\media/profile_images/'),
        ),
    ]
