# Generated by Django 4.0 on 2022-01-05 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0039_alter_student_faculty_alter_student_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('started_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(verbose_name='Confirm')),
                ('convo_num', models.AutoField(primary_key=True, serialize=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='users.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to='users.user')),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('message_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('message', models.TextField(max_length=500)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.conversation')),
            ],
        ),
    ]
