# Generated by Django 4.0 on 2022-01-05 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_student_faculty_alter_student_semester'),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='convo_num',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='creator', serialize=False, to='users.user'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.TextField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
