# Generated by Django 4.0 on 2022-01-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_remove_conversation_convo_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='msg_id',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
