# Generated by Django 4.0 on 2022-01-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_usermessage_msg_id_alter_usermessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='msg_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
